dream-aim-deliver/dad-e-class-monorepo

- .github/PULL_REQUEST_TEMPLATE/next_js_template.md
- .github/PULL_REQUEST_TEMPLATE/ui_kit_template.md
- README.md
@maany  Might need to change the lint command in the README, or add the proper one with `--fix`, right?
> Docs improvements

- packages/models/src/index.ts
- packages/models/src/language.ts
- packages/models/src/profile.ts
- packages/models/tests/profile.test.ts
> Models: add profile schemas and language enum

- packages/models/src/category.ts
- packages/models/src/eclass-package.ts
- packages/models/src/index.ts
- packages/models/src/topic.ts
- packages/models/tests/category.test.ts
- packages/models/tests/course.test.ts
- packages/models/tests/eclass-package.test.ts
- packages/models/tests/topic.test.ts
Implemented models for package, category, and topic, with tests.
Named "EClassPackage" instead of just "Package" since the latter is a reserved word.
> Course-related Models Pt. 1

- packages/ui-kit/lib/components/tabs/tab-trigger.tsx
- packages/ui-kit/stories/tabs-link.stories.tsx
- packages/ui-kit/stories/tabs.stories.tsx
> [TSK-635] [TSK-674] [TSK-675] migration(ui-kit): tabs 

- packages/models/src/index.ts
- packages/models/src/notification.ts
- packages/models/tests/notification.test.ts
> [TSK-664] Implementation of Notification model

- packages/models/src/coach-review.ts
- packages/models/src/coaching-offer.ts
- packages/models/src/coaching-session.ts
- packages/models/src/index.ts
- packages/models/tests/coach-review.test.ts
- packages/models/tests/coaching-offer.test.ts
- packages/models/tests/coaching-session.test.ts
> [TSK-636] feat(models): CoachingSession, CoachingOffering, CoachReview

- packages/ui-kit/lib/components/button.tsx
- packages/ui-kit/stories/button.stories.tsx
- Component name: 'Button`
- Figma link or screenshot: [Figma Design](https://www.figma.com/)
---
Fixes #83
> [TSK-749] migration(ui-kit):fix button

- packages/ui-kit/lib/components/avatar/user-avatar.tsx
- packages/ui-kit/lib/components/coursecard/course-creator.tsx
- packages/ui-kit/stories/user-avatar.stories.tsx
- packages/ui-kit/tests/user-avatar.test.tsx
- Component name: 'UserAvatar`
- Figma link or screenshot: [Figma Design](https://www.figma.com/)
---
Fixes #81
> [TSK-748] migration(ui-kit):fix UserAvatar

- .github/workflows/publish.yml
- packages/auth/project.json
- packages/models/project.json
- packages/translations/project.json
- packages/ui-kit/project.json
- tools/update-dependency-versions.py
Please go to the `Preview` tab and select the appropriate sub-template:
* [UI-Kit PR Template](?expand=1&template=ui_kit_template.md)
* [Next.js PR Template](?expand=1&template=next_js_template.md)
> [TSK-825] fix failing npm releases 

- .github/workflows/ci.yml
- apps/platform-e2e/tsconfig.json
- tools/check-nx-sync.sh
Introduce a script to verify that the Nx workspace is in sync during the CI process, ensuring consistency and preventing out-of-sync issues.
> [TSK-836] Add Nx sync check to CI workflow

- packages/ui-kit/.storybook/preview-head.html
Incorporate Google Fonts links into the Storybook preview head to force Storybook to render them.
> [TSK-843] Add Google Fonts to Storybook preview

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/coaching-on-demand-banner/coaching-on-demand-banner.tsx
- packages/ui-kit/stories/coaching-on-demand-banner.stories.tsx
- packages/ui-kit/tests/coaching-on-demand-banner.test.tsx
- Component name: `CoachingOnDemandBanner`
- Figma link or screenshot: [On figma](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6221-57970&t=IrCukPhd3jcco8aU-4).
---
---
Fixes #78
> [TSK-729] [TSK-730] [TSK-731] feat(ui-kit):Add new banner component for coaching on demand

- packages/ui-kit/lib/components/topic-list.tsx
- packages/ui-kit/stories/topic-link-list.stories.tsx
---
---
Fixes #77 
Hello @alebg, i have exported the  [Topic model](https://github.com/dream-aim-deliver/dad-e-class-monorepo/blob/main/packages/models/src/topic.ts) type but it not contain url as a string for navigation.
> [TSK-726] [TSK-727] [TSK-728] feat(topic-list): TopicLinkList

- packages/ui-kit/lib/components/accordion/accordion-content.tsx
- packages/ui-kit/lib/components/accordion/accordion-item.tsx
- packages/ui-kit/lib/components/accordion/accordion-trigger.tsx
- packages/ui-kit/lib/components/accordion/accordion.tsx
- packages/ui-kit/lib/components/accordion/index.ts
- packages/ui-kit/lib/components/rich-text-element/renderer.tsx
- packages/ui-kit/lib/index.ts
- packages/ui-kit/stories/accordion.stories.tsx
- Component name: `AccordionList'
**PR Overview**
This PR includes the following updates in the UI Kit:
- Accordion Component: Implemented the layout for the Accordion component.
- Storybook Integration: Added a Storybook entry for the Home Page Accordion.
- Bug Fix in RichTextRenderer: Introduced className as a prop to allow text customization.
---
---
Fixes #79
> [TSK-732] [TSK-733] [TSK-734] ui-kit:home-AccordionList

- packages/ui-kit/lib/components/footer.tsx
- packages/ui-kit/stories/footer.stories.tsx
- packages/ui-kit/tests/footer.test.tsx
- Component name: `Footer` 
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6239-45127&t=IrCukPhd3jcco8aU-4)
---
---
Fixes #80
> [TSK-735] [TSK-736] [TSK-737] ui-kit: Footer

- .github/PULL_REQUEST_TEMPLATE/ui_kit_template.md
Enhance the pull request template by incorporating a checklist focused on React best practices for component design, promoting better coding standards and practices among contributors.
> [TSK-850] Update PR template with React best practices checklist

- packages/ui-kit/lib/components/carousel/generalcard.tsx
- packages/ui-kit/lib/components/dropdown.tsx
- packages/ui-kit/lib/components/navbar.tsx
- packages/ui-kit/stories/carousel/general-card.stories.tsx
- packages/ui-kit/stories/navbar.stories.tsx
- Component name: `navbar-refactored ` , `General Card-refactored` , and `Dropdown-refactored`
---
---
Fixes #125
> [TSK-850] Refactor components to take out props from State, and properly wire state changes via callbacks, Part 1

- package.json
- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/home-banner/hero.tsx
- packages/ui-kit/lib/components/video-player.tsx
- packages/ui-kit/package.json
- packages/ui-kit/stories/hero.stories.tsx
- packages/ui-kit/stories/video-player.stories.tsx
- packages/ui-kit/tests/hero.test.tsx
- pnpm-lock.yaml
- Component name: `HomeBanner` 
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6241-97552&t=IrCukPhd3jcco8aU-4)
---
Fixes #75
> [TSK-720] [TSK-721] [TSK-722] feat(ui-kit): add HomeBanner and VideoPlayer components with storybook 

- packages/ui-kit/lib/components/course-intro-banner.tsx
- packages/ui-kit/stories/course-intro-banner.stories.tsx
- packages/ui-kit/tests/course-intro-banner.test.tsx
- Component name: `CourseIntroBanner Component`
In [figma](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=5675-78084&t=2ZDV6HJxfQDBvOSW-4).
Screenshot
---
---
Fixes #155
> feat(ui-kit): CourseIntroBanner component , storybook and test are added.

- packages/ui-kit/stories/course-card/course-card-list-checkbox-filter.stories.tsx
- Component name: `CourseCardList with checkbox filter variation`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6340-49697&t=pUvzvGlbr8ychX2x-4) 
---
---
Fixes #91
> [TSK-770] [TSK-771] [TSK-772] ui-kit: CourseCardList with checkbox filter variation

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/coaching-session-tracker/coaching-session-card.tsx
- packages/ui-kit/lib/components/coaching-session-tracker/coaching-session-item.tsx
- packages/ui-kit/lib/components/coaching-session-tracker/coaching-session-tracker.tsx
- packages/ui-kit/stories/coaching-session-tracker.stories.tsx
- packages/ui-kit/tests/coaching-session-tracker.test.tsx
- Component name: `CoachingSessionsTracker`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=5685-115255&t=2ZDV6HJxfQDBvOSW-4).
---
---
Fixes #154
> feat(ui-kit): coachingSessionTracker component , storybook and test are added.

- apps/platform-e2e/project.json
- apps/platform-e2e/src/auth-error-page.spec.ts
- apps/platform-e2e/tsconfig.json
- apps/platform/src/app/[locale]/auth/error/page.tsx
- apps/platform/src/components/home.tsx
- apps/platform/src/components/login-error.tsx
- apps/platform/src/components/login.tsx
- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/translations/src/lib/pages/home/home-de.ts
- packages/translations/src/lib/pages/home/home-en.ts
- packages/translations/src/lib/pages/login/login-de.ts
- packages/translations/src/lib/pages/login/login-en.ts
- packages/translations/src/lib/pages/sso/sso-de.ts
- packages/translations/src/lib/pages/sso/sso-en.ts
Please go to the `Preview` tab and select the appropriate sub-template:
* [UI-Kit PR Template](?expand=1&template=ui_kit_template.md)
* [Next.js PR Template](?expand=1&template=next_js_template.md)
> [TSK-821] - Style the Auth error page

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/module-pagination.tsx
- packages/ui-kit/stories/module-pagination.stories.tsx
- packages/ui-kit/tests/module-pagination.test.tsx
- Component name: `Module Pagination`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=7613-171160&t=Odg9AWgp943rCt3H-4)
---
---
Fixes #165
> [TSK-972] [TSK-973] ui-kit: ModulePagination

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/avatar/user-avatar.tsx
- packages/ui-kit/lib/components/group-course-banner.tsx
- packages/ui-kit/stories/group-course-banner.stories.tsx
- packages/ui-kit/tests/group-course-banner.test.tsx
feat(ui-kit): add GroupCourseBanner component with translations, stories and tests- Refactor user-avatar
Please go to the `Preview` tab and select the appropriate sub-template:
* [UI-Kit PR Template](?expand=1&template=ui_kit_template.md)
* [Next.js PR Template](?expand=1&template=next_js_template.md)
> [TSK-1015] - ui-kit: GroupCourseBanner

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/coaches-skeleton.tsx
- packages/ui-kit/lib/index.ts
- packages/ui-kit/stories/coaches-skeleton.stories.tsx
- packages/ui-kit/tests/coaches-skeleton.test.tsx
- Component name: `CoachesSkeleton`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=5255-40857&t=o1LCOVRMX0nNWKTi-4)
---
---
Fixes # (issue)
> [TSK-1029] ui-kit: CoachesSkeleton

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .gitignore
- .npmrc
- .npmrc.template
- tools/check-nx-sync.sh
This is required for the subsequent PRs that include CATS as a dependency.
> [TSK-1070] Copy GitHub Actions setup for authentication to registries for private packages

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/coaching-sessions/coaching-session-card.tsx
- packages/ui-kit/lib/components/coaching-sessions/student-coaching-session/student-action.tsx
- packages/ui-kit/lib/components/coaching-sessions/student-coaching-session/student-coaching-session-card.tsx
- packages/ui-kit/stories/coaching-sessions/coaching-session-card.stories.tsx
- packages/ui-kit/stories/coaching-sessions/coaching-session-list.stories.tsx
- packages/ui-kit/tests/coaching-session-list.test.tsx
- Component name: `CoachingSessionCard`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6854-244605&t=mKICRgUARi36OpzJ-4)
---
> [TSK-1013] ui-kit: ToBeDefined variant for CoachingSessionCard

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/buy-complete-package-banner.tsx
- packages/ui-kit/stories/buy-complete-package-banner.stories.tsx
- packages/ui-kit/tests/buy-complete-package-banner.test.tsx
- Component name: `BuyCompletePackageBanner`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6340-146872&t=chc7oUqrNOKvZB9P-4)
---
---
Fixes # (issue)
> [TSK-1052] ui-kit: BuyCompletePackageBanner

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/package-general-information-banner.tsx
- packages/ui-kit/lib/index.ts
- packages/ui-kit/stories/package-general-information-banner.stories.tsx
- packages/ui-kit/tests/package-general-information-banner.test.tsx
- Component name: `PackageGeneralInformation`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=3023-26309&t=RFEzfHq10EJ6cUE8-4)
---
---
Fixes # (issue)
> [TSK-1053] ui-kit: PackageGeneralInformation

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/add-coach-modal.tsx
- packages/ui-kit/lib/index.ts
- packages/ui-kit/stories/add-coach-modal.stories.tsx
- packages/ui-kit/tests/add-coach-modal.test.tsx
- Component name: `AddCoachModal`
- New component. Not in figma.
---
---
Fixes # (issue)
> [TSK-1123] - ui-kit: AddCoachModal

- packages/ui-kit/lib/components/coaching-sessions/coach-coaching-session/coach-action.tsx
- packages/ui-kit/lib/components/coaching-sessions/coach-coaching-session/coach-coaching-session-card.tsx
- packages/ui-kit/lib/components/coaching-sessions/coaching-session-card.tsx
- packages/ui-kit/lib/components/coaching-sessions/date-and-time.tsx
- packages/ui-kit/lib/components/coaching-sessions/review-card.tsx
- packages/ui-kit/lib/components/coaching-sessions/student-coaching-session/student-action.tsx
- packages/ui-kit/lib/components/coaching-sessions/student-coaching-session/student-coaching-session-card.tsx
- packages/ui-kit/stories/coaching-sessions/coaching-session-card.stories.tsx
- packages/ui-kit/stories/coaching-sessions/coaching-session-list.stories.tsx
- packages/ui-kit/tests/coaching-session-card.test.tsx
- packages/ui-kit/tests/coaching-session-list.test.tsx
- Component name: `CoachingSession Card`
- Figma link or screenshot: [Figma Design](https://www.figma.com/)
---
---
Fixes #251
> ui-kit: CoachingSessionCard refactor for variants and typing

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/book-session-with-banner.tsx
- packages/ui-kit/lib/index.ts
- packages/ui-kit/stories/book-session-with-banner.stories.tsx
- packages/ui-kit/tests/book-session-with-banner.test.tsx
- Component name: `BookSessionWith`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=5685-99344&t=VMyyZFrRyWLmVtbt-4)
---
> [TSK-1126] ui-kit: BookSessionWithCoach (banner)

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/buy-coaching-session-banner.tsx
- packages/ui-kit/lib/index.ts
- packages/ui-kit/stories/buy-coaching-session-banner.stories.tsx
- packages/ui-kit/tests/buy-coaching-session-banner.test.tsx
- Component name: `BuyCoachingSessionBanner`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=5272-80017&t=hA55frAviiwBbq5W-4)
---
> [TSK-1128] ui-kit: BuyCoachingSessionBanner

- apps/platform/src/app/[locale]/(mock-pages)/edit/course/[slug]/page.tsx
- apps/platform/src/lib/infrastructure/client/pages/workspace/edit/edit-course.tsx
- apps/platform/src/lib/infrastructure/server/pages/workspace/edit-course-rsx.tsx
Now query parameter tab helps return to the same tab. The best usecase is reload on save.
> Add URL navigation between edit course tabs

- apps/platform/src/lib/infrastructure/client/pages/common/hooks/use-course-image-upload.ts
- apps/platform/src/lib/infrastructure/client/pages/workspace/edit/edit-lesson-components.tsx
- apps/platform/src/lib/infrastructure/client/pages/workspace/edit/hooks/use-accordion-icon-upload.ts
- apps/platform/src/lib/infrastructure/client/pages/workspace/edit/hooks/use-introduction-video-upload.ts
- apps/platform/src/lib/infrastructure/common/mocks/mock-router.ts
- apps/platform/src/lib/infrastructure/common/mocks/procedures/course-image.ts
- packages/auth/package.json
- packages/models/src/usecase-models/get-course-access-usecase-models.ts
- packages/ui-kit/lib/utils/file-utils.ts
- pnpm-lock.yaml
Enhance course management by integrating course outline fetching, saving, and handling not found cases. Fix routing for workspace and user courses, while addressing build and lint errors. Update dependencies and improve file upload handling for course images.
> [TSK-1301] Integrate course management features and fix routing issues

- apps/platform/src/app/[locale]/(wired-pages)/error.tsx
- apps/platform/src/app/[locale]/(wired-pages)/not-found.tsx
- apps/platform/src/lib/infrastructure/client/pages/workspace/create-course.tsx
- apps/platform/src/lib/infrastructure/server/pages/workspace/create-course-rsc.tsx
> Integrate create course

- apps/platform/src/lib/infrastructure/client/pages/course/enrolled-course/enrolled-course-preview.tsx
- apps/platform/src/lib/infrastructure/client/pages/workspace/edit/edit-lesson-components.tsx
- apps/platform/src/lib/infrastructure/client/pages/workspace/edit/utils/transform-modules.ts
- packages/ui-kit/lib/components/introduction-form.tsx
Enhance course management by integrating course outline fetching, saving, and lesson editing features. Address multiple bugs related to routing, error handling, and user interface elements. Update dependencies for improved functionality and consistency.
> Integrate course management features and fix various issues

- packages/models/src/usecase-models/list-coach-students-usecase-models.ts
- packages/models/src/usecase-models/list-coaches-usecase-models.ts
- packages/models/src/usecase-models/list-course-students-usecase-models.ts
Introduce new schemas for handling requests and responses related to listing coach students and course students, enhancing the application's data handling capabilities.
> Add use case models for listing coach and course students

- packages/models/src/usecase-models/list-course-students-usecase-models.ts
Introduce a new boolean field to indicate if a student is associated with a coach in the course response schema.
> Add isStudentOfCoach field to ListCourseStudentsSuccessResponseSchema

- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/stepper/stepper-context.tsx
- packages/ui-kit/lib/components/stepper/stepper-controls.tsx
- packages/ui-kit/lib/components/stepper/stepper-item.tsx
- packages/ui-kit/lib/components/stepper/stepper-list.tsx
- packages/ui-kit/lib/components/stepper/stepper.tsx
- packages/ui-kit/lib/index.ts
- packages/ui-kit/stories/stepper.stories.tsx
- packages/ui-kit/tests/stepper.test.tsx
- Component name: `Stepper`
- Figma link or screenshot: [Figma Design](https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6385-175064&t=MvFuTlSNsXlLIs2T-4)
---
> ui-kit: Stepper component

- apps/platform/src/lib/infrastructure/client/hooks/use-list-course-materials-presenter.ts
- apps/platform/src/lib/infrastructure/client/pages/course/enrolled-course/enrolled-course-material.tsx
- apps/platform/src/lib/infrastructure/client/pages/course/enrolled-course/enrolled-course-students.tsx
- apps/platform/src/lib/infrastructure/client/pages/course/enrolled-course/enrolled-course.tsx
- apps/platform/src/lib/infrastructure/common/mocks/mock-router.ts
- apps/platform/src/lib/infrastructure/common/mocks/procedures/course-materials.ts
- apps/platform/src/lib/infrastructure/common/presenters/course-materials-presenter.ts
- docker-compose.yml
- packages/models/src/usecase-models/index.ts
- packages/models/src/view-models/course-materials-view-model.ts
- packages/models/src/view-models/index.ts
- packages/translations/src/lib/dictionaries/base.ts
- packages/translations/src/lib/dictionaries/de.ts
- packages/translations/src/lib/dictionaries/en.ts
- packages/ui-kit/lib/components/accordion/accordion-trigger.tsx
- packages/ui-kit/lib/components/accordion/course-materials-accordion.tsx
- packages/ui-kit/lib/index.ts
- packages/ui-kit/stories/card-accordion.stories.tsx
Hello @carlapbg, I have created the course student-material section. Could you please check the UI? I have made it as per our discussion.If it needs any updates, I can make the necessary changes.
#73
> Implement Course Material Tab
